import Head from 'next/head';

import { Header } from '@/components/header';
import Layout from '@/components/layout';
import Sorting from '@/containers/home/sorting';

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ paddingTop: '4rem' }}>
        <Header isTop={true} />
        <Layout>
          <Sorting />
        </Layout>
      </main>
    </>
  );
};

export default Home;
